import 'package:flutter/material.dart';
import 'package:flutterapp/fitnessapp/generatedframe1widget1/generated/GeneratedGroup1Widget1.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1010.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 960.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 69, 72, 71),
                              ),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1243.526611328125,
                              height: 1010.0,
                              child: GeneratedGroup1Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
