import 'package:flutter/material.dart';
import 'package:flutterapp/fitnessapp/generatedframe1widget/generated/GeneratedSection1Widget.dart';
import 'package:flutterapp/fitnessapp/generatedframe1widget/generated/GeneratedSection2Widget.dart';
import 'package:flutterapp/fitnessapp/generatedframe1widget/generated/GeneratedSection3Widget.dart';
import 'package:flutterapp/fitnessapp/generatedframe1widget/generated/GeneratedNavWidget.dart';
import 'package:flutterapp/fitnessapp/generatedframe1widget/generated/GeneratedGroup148Widget.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 4649.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 4649.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 0, 0, 0),
                              ),
                            ),
                            Positioned(
                              left: 66.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 1343.0,
                              height: 1170.0,
                              child: GeneratedSection1Widget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 1200.0,
                              height: 22.0,
                              child: GeneratedNavWidget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 1030.0,
                              right: null,
                              bottom: null,
                              width: 1199.0,
                              height: 767.0,
                              child: GeneratedSection2Widget(),
                            ),
                            Positioned(
                              left: 89.70159912109375,
                              top: 1997.0,
                              right: null,
                              bottom: null,
                              width: 1350.29833984375,
                              height: 1439.0,
                              child: GeneratedSection3Widget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 3586.0,
                              right: null,
                              bottom: null,
                              width: 1200.2169189453125,
                              height: 920.0,
                              child: GeneratedGroup148Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
